name: Build and Test Hive

on:
  push:
    branches: ["main"]
    paths: ["hive/**", ".github/workflows/**"]
  workflow_dispatch:

jobs:
  hive_test_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: Run Tests
        run: make test

      - name: golang-govulncheck-action
        uses: golang/govulncheck-action@v1.0.4
#      - name: Security reports
#        run: make security
