name: Hive Build and Test

on:
  push:
    branches:
      - main
      - test
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - Makefile
      - .github/workflows/hive.yml
  pull_request:
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - Makefile
      - .github/workflows/hive.yml
  workflow_dispatch:

jobs:
  build_and_test:
    name: Hive Build and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"

      - name: Build Hive
        run: make build

      - name: Run Tests
        run: make test

  lint_and_security:
    name: Hive Lint and Security
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"

      - name: Check Format
        run: make check-format

      - name: Go Vet
        run: make vet

      - name: Security Checks
        run: make security-check
