name: UI Build and Test

on:
  push:
    branches:
      - main
      - ui
    paths:
      - hive/services/hiveui/frontend/**
      - .github/workflows/ui.yml
  pull_request:
    paths:
      - hive/services/hiveui/frontend/**
      - .github/workflows/ui.yml
  workflow_dispatch:

jobs:
  ui_build_and_test:
    name: UI Build and Test
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: hive/services/hiveui/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          sparse-checkout: hive/services/hiveui/frontend

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: hive/services/hiveui/frontend/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          cache-dependency-path: hive/services/hiveui/frontend/pnpm-lock.yaml
          node-version-file: hive/services/hiveui/frontend/.nvmrc

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome Check
        run: pnpm check

      - name: Build Frontend
        run: pnpm build
